name: WildStock
version: '1.0-SNAPSHOT'
main: org.stocks.wildStock.WildStock
api-version: '1.21'
commands:
  stock:
    description: 주식 창을 엽니다.
    usage: /<command>
  shop:
    description: 상점 창을 엽니다.
    usage: /<command>
  pause:
    description: 주식 변동을 정지/재시작 합니다.
    usage: /<command>
